/* Review manifest; render the pages named by file in order. */
const slides = [
  {
    "order": 1,
    "file": "1page.html",
    "title": "자율형 기업을 위한SAP BTP Agent 데모",
    "status": "existing",
    "purpose": "Open the deck with the autonomous enterprise ambition.",
    "keyMessage": "SAP BTP provides the foundation for context-aware enterprise agents.",
    "changes": "Retained as the opening cover.",
    "visualAudit": "KEEP VISUAL"
  },
  {
    "file": "agenda.html",
    "title": "발표 순서",
    "status": "new",
    "purpose": "Orient the audience to the five sections.",
    "keyMessage": "Vision, agent execution, control, platform and demonstration form one story.",
    "changes": "Added a five-section agenda.",
    "visualAudit": "UPDATED",
    "kind": "agenda",
    "order": 2
  },
  {
    "file": "divider-01-vision.html",
    "title": "Autonomous Enterprise",
    "status": "new",
    "purpose": "Introduce section 01: 비전과 업무 문맥.",
    "keyMessage": "From business ambition to a connected AI foundation",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "Autonomous Enterprise",
    "sectionNumber": "01",
    "order": 3
  },
  {
    "order": 4,
    "file": "2page.html",
    "title": "우리가 지향하는 자율형 기업",
    "status": "existing",
    "purpose": "Frame the shift from fragmented manual work to autonomous operations.",
    "keyMessage": "Enterprise work can move from manual coordination to controlled autonomy.",
    "changes": "Retained as the opening vision slide.",
    "visualAudit": "TOO TEXT-HEAVY",
    "section": "Autonomous Enterprise",
    "sectionNumber": "01"
  },
  {
    "file": "ai-native.html",
    "title": "AI-First에서 AI-Native로",
    "status": "new",
    "purpose": "Explain the software, scope and data shifts behind autonomous enterprise.",
    "keyMessage": "Move from a tool, an app boundary and records to execution, landscape and business context.",
    "changes": "Refined the PDF comparison into a single visual-led page.",
    "visualAudit": "UPDATED",
    "section": "Autonomous Enterprise",
    "sectionNumber": "01",
    "order": 5
  },
  {
    "order": 6,
    "file": "3page.html",
    "title": "업무 문맥을 이해해야 Agent가 올바르게 실행",
    "status": "new",
    "purpose": "Explain why enterprise AI needs more than a generic LLM.",
    "keyMessage": "Autonomous AI requires data, process, knowledge, identity, and policy context.",
    "changes": "New bridge between the autonomous-enterprise vision and the solution foundation.",
    "visualAudit": "SIMPLIFY",
    "section": "Autonomous Enterprise",
    "sectionNumber": "01"
  },
  {
    "order": 7,
    "file": "4page.html",
    "title": "업무를 연결하는 공통 AI 기반",
    "status": "revised",
    "beforeFile": "../lges_customer/3page.html",
    "purpose": "Show how shared enterprise intelligence supports applications and agents.",
    "keyMessage": "Connected applications build on one shared AI and knowledge foundation.",
    "changes": "Moved after business context and reframed as the solution vision.",
    "visualAudit": "REDESIGN · TOO UI-LIKE",
    "section": "Autonomous Enterprise",
    "sectionNumber": "01"
  },
  {
    "order": 8,
    "file": "5page.html",
    "title": "팀 경계를 넘어 연결되는 자율형 업무",
    "status": "revised",
    "beforeFile": "../lges_customer/4page.html",
    "purpose": "Show cross-functional autonomy rather than isolated AI applications.",
    "keyMessage": "Teams share context, orchestration, governance, and reusable capabilities.",
    "changes": "Restored a small rendering of the slide 4 foundation in all six team cards.",
    "visualAudit": "UPDATED",
    "section": "Autonomous Enterprise",
    "sectionNumber": "01"
  },
  {
    "file": "divider-02-agents.html",
    "title": "Agentic Execution",
    "status": "new",
    "purpose": "Introduce section 02: Agent 경험과 실행.",
    "keyMessage": "From business intent to accountable action",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "Agentic Execution",
    "sectionNumber": "02",
    "order": 9
  },
  {
    "order": 10,
    "file": "8page.html",
    "title": "자율형 업무를 구성하는 네 가지 핵심 역량",
    "status": "new",
    "purpose": "Group technologies by the role they play in connected autonomy.",
    "keyMessage": "Experience, context, build, and execution work as one capability system.",
    "changes": "New orientation slide before detailed capability pages.",
    "visualAudit": "SIMPLIFY",
    "agents": "Joule · Harness · Deep Agent · 전문 Agent",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 11,
    "file": "10page.html",
    "title": "SAP 업무에 연결되는 Joule 경험",
    "status": "revised",
    "beforeFile": "../lges_customer/8page.html",
    "purpose": "Show the SAP-facing entry point for AI-assisted work.",
    "keyMessage": "Joule brings AI into the SAP work experience.",
    "changes": "Title made message-led and moved into the capability narrative.",
    "visualAudit": "TOO TEXT-HEAVY",
    "agents": "Joule Assistant · SAP 업무 진입점",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 12,
    "file": "9page.html",
    "title": "전사 지식을 연결해 업무 관계를 이해",
    "status": "revised",
    "beforeFile": "../lges_customer/7page.html",
    "purpose": "Explain how enterprise meaning and relationships become agent context.",
    "keyMessage": "A knowledge graph connects distributed information to business meaning.",
    "changes": "Repositioned in the knowledge layer; title made message-led.",
    "visualAudit": "TOO TEXT-HEAVY",
    "agents": "HANA Knowledge Graph · Agent의 판단 근거",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 13,
    "file": "6page.html",
    "title": "하나의 업무 요청에서 검증된 실행까지",
    "status": "new",
    "purpose": "Connect all major capabilities into one business flow.",
    "keyMessage": "A request travels through context, planning, coordination, validation, and outcome.",
    "changes": "New end-to-end story slide.",
    "visualAudit": "REDESIGN",
    "agents": "Joule → Harness / Deep Agent → 전문 Agent",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 14,
    "file": "7page.html",
    "title": "판단 · 실행 · 검증을 통제된 순환으로",
    "status": "new",
    "purpose": "Make the internal loop of an autonomous agent easy to understand.",
    "keyMessage": "Agents understand, retrieve, reason, plan, execute, validate, and escalate.",
    "changes": "New operational model slide.",
    "visualAudit": "SIMPLIFY",
    "agents": "Agent · 요청 이해부터 판단·실행·검증까지",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 15,
    "file": "11page.html",
    "title": "업무 요청을 분석과 실행으로 연결",
    "status": "revised",
    "beforeFile": "../lges_customer/9page.html",
    "purpose": "Introduce coordinated execution as a capability, not an isolated product.",
    "keyMessage": "Harness turns a request into coordinated work.",
    "changes": "Title made message-led and placed before Deep Agent and A2A.",
    "visualAudit": "TOO TEXT-HEAVY",
    "agents": "Harness Assistant · 분석과 업무 조율",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 16,
    "file": "12page.html",
    "title": "단순한 답변을 넘어 복합 업무를 계획하는 Agent",
    "status": "revised",
    "beforeFile": "../lges_customer/10page.html",
    "purpose": "Explain planning beyond a single assistant response.",
    "keyMessage": "Deep Agent creates accountable plans across a complex task.",
    "changes": "Title made message-led within the orchestration progression.",
    "visualAudit": "REDESIGN",
    "agents": "Deep Agent · 근거 수집과 복합 업무 계획",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 17,
    "file": "13page.html",
    "title": "전문 Agent가 협업해 하나의 업무를 완수",
    "status": "revised",
    "beforeFile": "../lges_customer/11page.html",
    "purpose": "Explain collaboration between specialized agents and applications.",
    "keyMessage": "A2A coordinates specialists across the business process.",
    "changes": "Title made message-led within the orchestration progression.",
    "visualAudit": "REDESIGN",
    "agents": "영업 · 생산 · 구매 Agent / A2A",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "file": "divider-03-control.html",
    "title": "Human Oversight & Governance",
    "status": "new",
    "purpose": "Introduce section 03: 사람의 통제와 거버넌스.",
    "keyMessage": "Human intent and enterprise governance at every level",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "Human Oversight & Governance",
    "sectionNumber": "03",
    "order": 18
  },
  {
    "order": 19,
    "file": "14page.html",
    "title": "자율성은 높이고, 사람의 통제는 유지",
    "status": "new",
    "purpose": "Show that autonomy scales with human control and risk.",
    "keyMessage": "People govern intent and exceptions while agents execute within guardrails.",
    "changes": "New controlled-autonomy maturity model.",
    "visualAudit": "SIMPLIFY",
    "agents": "전체 Agent · 승인·허용 범위·예외 처리",
    "section": "Human Oversight & Governance",
    "sectionNumber": "03"
  },
  {
    "order": 20,
    "file": "15page.html",
    "title": "Agent의 모든 실행에 Governance를 내재화",
    "status": "new",
    "purpose": "Show the controls required to operate agents responsibly.",
    "keyMessage": "Governance is built into how agents are built, run, and observed.",
    "changes": "New build-run-observe governance model.",
    "visualAudit": "SIMPLIFY",
    "agents": "전체 Agent · 인증·정책·실행 추적",
    "section": "Human Oversight & Governance",
    "sectionNumber": "03"
  },
  {
    "file": "divider-04-platform.html",
    "title": "SAP BTP Architecture",
    "status": "new",
    "purpose": "Introduce section 04: 플랫폼과 아키텍처.",
    "keyMessage": "The platform and architecture behind enterprise agents",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "SAP BTP Architecture",
    "sectionNumber": "04",
    "order": 21
  },
  {
    "order": 22,
    "file": "16page.html",
    "title": "왜 SAP BTP인가?",
    "status": "revised",
    "beforeFile": "../lges_customer/15page.html",
    "purpose": "Connect the autonomous model to SAP BTP's enterprise platform value.",
    "keyMessage": "SAP BTP combines business context, integration, and extension capabilities.",
    "changes": "Moved after the operating model and governance rationale.",
    "visualAudit": "TOO TEXT-HEAVY",
    "section": "SAP BTP Architecture",
    "sectionNumber": "04"
  },
  {
    "order": 23,
    "file": "17page.html",
    "title": "왜 운영에도 SAP BTP인가?",
    "status": "revised",
    "beforeFile": "../lges_customer/16page.html",
    "purpose": "Extend the BTP case to operating and lifecycle needs.",
    "keyMessage": "Enterprise operations require lifecycle, observability, and integration discipline.",
    "changes": "Moved after the BTP value proposition.",
    "visualAudit": "TOO TEXT-HEAVY",
    "section": "SAP BTP Architecture",
    "sectionNumber": "04"
  },
  {
    "order": 24,
    "file": "19page.html",
    "title": "SAP BTP Standard Architecture",
    "status": "revised",
    "beforeFile": "../lges_customer/13page.html",
    "purpose": "Show the standard architecture context for the solution.",
    "keyMessage": "The solution fits within a BTP standard architecture.",
    "changes": "Reordered into the architecture section.",
    "visualAudit": "SIMPLIFY",
    "section": "SAP BTP Architecture",
    "sectionNumber": "04"
  },
  {
    "order": 25,
    "file": "20page.html",
    "title": "SAP BTP Kyma 기반 App-in-App Portal Architecture",
    "status": "revised",
    "beforeFile": "../lges_customer/14page.html",
    "purpose": "Show the implementation architecture for the portal experience.",
    "keyMessage": "The portal architecture operationalizes the connected experience on BTP.",
    "changes": "Reordered into the architecture section.",
    "visualAudit": "SIMPLIFY",
    "section": "SAP BTP Architecture",
    "sectionNumber": "04"
  },
  {
    "order": 26,
    "file": "18page.html",
    "title": "참조 SAP BTP아키텍처와 비용",
    "status": "revised",
    "beforeFile": "../lges_customer/12page.html",
    "purpose": "Provide the reference architecture after the business rationale is established.",
    "keyMessage": "The platform architecture supports the connected autonomous model.",
    "changes": "Reordered into the architecture section.",
    "visualAudit": "KEEP VISUAL",
    "section": "SAP BTP Architecture",
    "sectionNumber": "04"
  },
  {
    "file": "21page.html",
    "title": "Autonomous App-in-App Demo",
    "status": "revised",
    "purpose": "Introduce section 05: 데모와 비즈니스 가치.",
    "keyMessage": "Show the operating model, then the business value",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "Autonomous App-in-App Demo",
    "sectionNumber": "05",
    "order": 27
  },
  {
    "order": 28,
    "file": "22page.html",
    "title": "자율형 업무 SCM 데모",
    "status": "revised",
    "beforeFile": "../lges_customer/18page.html",
    "purpose": "Demonstrate increasing levels of autonomy in SCM scenarios.",
    "keyMessage": "The scenarios progress from a task to exception resolution to orchestration.",
    "changes": "Moved into the proof section.",
    "visualAudit": "TOO TEXT-HEAVY",
    "agents": "영업 · 생산 · 구매 Agent",
    "section": "Autonomous App-in-App Demo",
    "sectionNumber": "05"
  },
  {
    "order": 29,
    "file": "23page.html",
    "title": "반복 조율은 줄이고, 중요한 판단에 집중",
    "status": "new",
    "purpose": "Close with the operational value of controlled autonomy.",
    "keyMessage": "Agents reduce coordination work so people can focus on decisions and exceptions.",
    "changes": "New conclusion slide.",
    "visualAudit": "SIMPLIFY",
    "section": "Autonomous App-in-App Demo",
    "sectionNumber": "05"
  }
];
