/* Review manifest; render the pages named by file in order. */
const slides = [
  {
    "order": 1,
    "file": "1page.html",
    "title": "Autonomous Enterprise SAP BAIP Agent Demo",
    "status": "existing",
    "purpose": "Open the deck with the autonomous enterprise ambition.",
    "keyMessage": "SAP BAIP provides the foundation for context-aware enterprise agents.",
    "changes": "Retained as the opening cover.",
    "visualAudit": "KEEP VISUAL"
  },
  {
    "order": 2,
    "file": "thumbnail-showcase.html",
    "title": "App Builder · Harness · Live Assistant",
    "status": "new",
    "purpose": "Show original App Builder, Harness and Live Assistant thumbnails on a dedicated slide.",
    "keyMessage": "Live App Builder and Harness workflows.",
    "changes": "Dedicated title-free thumbnail slide with bordered app GIFs and looping Live Assistant video.",
    "visualAudit": "UPDATED"
  },
  {
    "file": "agenda.html",
    "title": "Presentation Agenda",
    "status": "new",
    "purpose": "Orient the audience to four sections: enterprise and governance, execution, architecture, demo and value.",
    "keyMessage": "Vision, agent execution, control, platform and demonstration form one story.",
    "changes": "Updated to the four-section presentation agenda.",
    "visualAudit": "UPDATED",
    "kind": "agenda",
    "order": 3
  },
  {
    "file": "divider-01-vision.html",
    "title": "Autonomous Enterprise & Governance",
    "status": "new",
    "purpose": "Introduce the AI-Native enterprise vision, Business Context and governed Execution Loop.",
    "keyMessage": "AI-Native, core capabilities, Business Context and the governed Execution Loop establish enterprise principles.",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "Autonomous Enterprise & Governance",
    "sectionNumber": "01",
    "order": 4,
    "agents": ""
  },
  {
    "file": "ai-native.html",
    "title": "AI-First → AI-Native",
    "status": "new",
    "purpose": "Explain the software, scope and data shifts behind autonomous enterprise.",
    "keyMessage": "Move from a tool, an app boundary and records to execution, landscape and business context.",
    "changes": "Refined the PDF comparison into a single visual-led page.",
    "visualAudit": "UPDATED",
    "section": "Autonomous Enterprise & Governance",
    "sectionNumber": "01",
    "order": 5
  },
  {
    "order": 6,
    "file": "8page.html",
    "title": "Four Core Capabilities",
    "status": "new",
    "purpose": "Summarize Workflow, Context, Build and Execution as capabilities of the integrated model.",
    "keyMessage": "Capabilities span the composition rather than mapping one-to-one to products.",
    "changes": "Added original SAP PDF page 15 interoperability visual above the integrated capability map.",
    "visualAudit": "SIMPLIFY",
    "agents": "Joule + Harness + App Builder",
    "section": "Autonomous Enterprise & Governance",
    "sectionNumber": "01"
  },
  {
    "order": 7,
    "file": "3page.html",
    "title": "Agent Workflow & Governance",
    "status": "new",
    "purpose": "Explain SAP portfolio-wide Agent Workflow & Governance using the original SAP PDF page 29 visual.",
    "keyMessage": "Joule orchestrates agents across SAP business domains; AI Foundation supports Custom AI, with built-in Security & Compliance across the portfolio.",
    "changes": "Reframed page 6 as the detailed counterpart to Agent Workflow & Governance, with original PDF page 29 artwork and Korean supporting explanations.",
    "visualAudit": "SIMPLIFY",
    "section": "Autonomous Enterprise & Governance",
    "sectionNumber": "01"
  },
  {
    "order": 8,
    "file": "7page.html",
    "title": "Business Context",
    "status": "new",
    "purpose": "Make the internal loop of an autonomous agent easy to understand.",
    "keyMessage": "Agents understand, retrieve, reason, plan, execute, validate, and escalate.",
    "changes": "Moved into agenda 01 to explain Business Context and the governed Execution Loop before Human Oversight.",
    "visualAudit": "SIMPLIFY",
    "agents": "Agent · 요청 이해부터 판단·실행·검증까지",
    "section": "Autonomous Enterprise & Governance",
    "sectionNumber": "01"
  },
  {
    "file": "app-ai-development-draft.html",
    "title": "App & AI Development",
    "status": "draft",
    "purpose": "Explain App & AI Development as a business concept integrated into four lifecycle cards.",
    "keyMessage": "App Builder connects business requests, AI-assisted development, validation and application reuse.",
    "changes": "Replaced the 3D illustration with a 2D UI concept montage referencing supplied SAP AI PDF page 9, Joule as new AI UX Layer; retained four business lifecycle cards.",
    "visualAudit": "DRAFT",
    "section": "Autonomous Enterprise & Governance",
    "sectionNumber": "01",
    "agents": "App Builder",
    "order": 9
  },
  {
    "order": 10,
    "file": "6page.html",
    "title": "Agentic Execution — Integrated Operating Model",
    "status": "new",
    "purpose": "Explain how Joule, Harness and App Builder combine in the intended operating model.",
    "keyMessage": "Harness orchestrates SAP execution through Joule and tools; App Builder extends capabilities through a conditional reviewed build path.",
    "changes": "Promoted the conditional App Builder -> Validate/Approve/Release -> Reuse path into the UI image; removed duplicate below-image text and shortened four role cards.",
    "visualAudit": "REDESIGN",
    "agents": "Joule + Harness + App Builder",
    "section": "Autonomous Enterprise & Governance",
    "sectionNumber": "01"
  },
  {
    "file": "divider-02-agents.html",
    "title": "Agentic Execution",
    "status": "new",
    "purpose": "Introduce section 02: Agentic Execution.",
    "keyMessage": "Integrated Operating Model과 Human + Agent 역할 분담에서 개별 Agent의 실행·협업으로 연결",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "Agentic Execution",
    "sectionNumber": "02",
    "order": 11
  },
  {
    "order": 12,
    "file": "10page.html",
    "title": "Joule — SAP Data 접근과 업무 실행",
    "status": "revised",
    "beforeFile": "../lges_customer/8page.html",
    "purpose": "Show the SAP-facing entry point for AI-assisted work.",
    "keyMessage": "Joule brings AI into the SAP work experience.",
    "changes": "Title made message-led and moved into the capability narrative.",
    "visualAudit": "TOO TEXT-HEAVY",
    "agents": "Joule Assistant · SAP 업무 진입점",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 13,
    "file": "llm-wiki-explanation.html",
    "title": "LLM Wiki — 팀 지식 축적과 요청 맥락 재활용",
    "status": "restored",
    "purpose": "Restore the dedicated LLM Wiki comparison from supplied dry-run PDF page 6.",
    "keyMessage": "Team knowledge and request/answer history provide reusable context for AI.",
    "changes": "Restored PDF page 6 as editable HTML; placed immediately before HANA Knowledge Graph.",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 14,
    "file": "9page.html",
    "title": "HANA Knowledge Graph — Business Context 연결",
    "status": "revised",
    "beforeFile": "../lges_customer/7page.html",
    "purpose": "Explain how enterprise meaning and relationships become agent context.",
    "keyMessage": "A knowledge graph connects distributed information to business meaning.",
    "changes": "Expanded to three scenarios: manual work, Agent without the capability, and Agent with the capability; kept the shared App Builder card style.",
    "visualAudit": "TOO TEXT-HEAVY",
    "agents": "HANA Knowledge Graph · Agent의 판단 근거",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 15,
    "file": "11page.html",
    "title": "Harness — 업무 판단과 실행 조율",
    "status": "revised",
    "beforeFile": "../lges_customer/9page.html",
    "purpose": "Introduce coordinated execution as a capability, not an isolated product.",
    "keyMessage": "Harness turns a request into coordinated work.",
    "changes": "Expanded to three scenarios: manual work, Agent without the capability, and Agent with the capability; kept the shared App Builder card style.",
    "visualAudit": "TOO TEXT-HEAVY",
    "agents": "Harness Assistant · 분석과 업무 조율",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "file": "app-builder-explanation.html",
    "title": "App Builder — App 변경과 배포",
    "status": "restored",
    "purpose": "Explain the original App Builder scenario using editable HTML from the user-supplied 5page.html.",
    "keyMessage": "App Builder adapts document processing code, deploys changes and enables reprocessing rather than relying on repeated IT development requests.",
    "changes": "Rebuilt the three process lanes, cost badges and two capabilities from user-supplied HTML in the official template.",
    "visualAudit": "ORIGINAL USER SCENARIO",
    "section": "Agentic Execution",
    "sectionNumber": "02",
    "agents": "App Builder",
    "order": 16
  },
  {
    "order": 17,
    "file": "12page.html",
    "title": "Harness Deep Agent — 복합 분석과 계획",
    "status": "revised",
    "beforeFile": "../lges_customer/10page.html",
    "purpose": "Explain planning beyond a single assistant response.",
    "keyMessage": "Deep Agent creates accountable plans across a complex task.",
    "changes": "Restored detailed scenario and flow from user-supplied original HTML; retained official template and current slide order.",
    "visualAudit": "REDESIGN",
    "agents": "Deep Agent · 근거 수집과 복합 업무 계획",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "order": 18,
    "file": "13page.html",
    "title": "Harness A2A — Cross-Team 협업",
    "status": "revised",
    "beforeFile": "../lges_customer/11page.html",
    "purpose": "Explain collaboration between specialized agents and applications.",
    "keyMessage": "A2A coordinates specialists across the business process.",
    "changes": "Restored detailed scenario and flow from user-supplied original HTML; retained official template and current slide order.",
    "visualAudit": "REDESIGN",
    "agents": "영업 · 생산 · 구매 Agent / A2A",
    "section": "Agentic Execution",
    "sectionNumber": "02"
  },
  {
    "file": "divider-04-platform.html",
    "title": "SAP BAIP Architecture",
    "status": "new",
    "purpose": "Introduce section 03: SAP BAIP Architecture.",
    "keyMessage": "SAP BAIP 기반의 구현 구조와 운영",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "SAP BAIP Architecture",
    "sectionNumber": "03",
    "order": 19
  },
  {
    "order": 20,
    "file": "19page.html",
    "title": "SAP BAIP — Standard Architecture",
    "status": "revised",
    "beforeFile": "../lges_customer/13page.html",
    "purpose": "Present the original reference architecture from the user dry-run PDF file page 13.",
    "keyMessage": "Agent Harness connects SAP Kyma, SAP Build, AI services and business systems.",
    "changes": "Restored the original architecture image from supplied dry-run PDF page 13 without modifying its contents.",
    "visualAudit": "SIMPLIFY",
    "section": "SAP BAIP Architecture",
    "sectionNumber": "03"
  },
  {
    "order": 21,
    "file": "20page.html",
    "title": "SAP BAIP — Kyma App-in-App Architecture",
    "status": "revised",
    "beforeFile": "../lges_customer/14page.html",
    "purpose": "Show the implementation architecture for the portal experience.",
    "keyMessage": "The portal architecture operationalizes the connected experience on BAIP.",
    "changes": "Recreated the architecture visual using the supplied Bring Your Own Agent reference style; retained current workload, service, protocol and external-system labels.",
    "visualAudit": "SIMPLIFY",
    "section": "SAP BAIP Architecture",
    "sectionNumber": "03"
  },
  {
    "order": 22,
    "file": "16page.html",
    "title": "SAP BAIP — Platform Value & TCO",
    "status": "revised",
    "beforeFile": "../lges_customer/15page.html",
    "purpose": "Connect the autonomous model to SAP BAIP's enterprise platform value.",
    "keyMessage": "SAP BAIP combines business context, integration, and extension capabilities.",
    "changes": "Moved after the operating model and governance rationale.",
    "visualAudit": "TOO TEXT-HEAVY",
    "section": "SAP BAIP Architecture",
    "sectionNumber": "03"
  },
  {
    "order": 23,
    "file": "17page.html",
    "title": "SAP BAIP — Operations & OPEX",
    "status": "revised",
    "beforeFile": "../lges_customer/16page.html",
    "purpose": "Extend the BAIP case to operating and lifecycle needs.",
    "keyMessage": "Enterprise operations require lifecycle, observability, and integration discipline.",
    "changes": "Moved after the BAIP value proposition.",
    "visualAudit": "TOO TEXT-HEAVY",
    "section": "SAP BAIP Architecture",
    "sectionNumber": "03"
  },
  {
    "file": "21page.html",
    "title": "Demo & Business Value",
    "status": "revised",
    "purpose": "Introduce section 04: Demo & Business Value.",
    "keyMessage": "조직의 문제에서 SCM 실행과 Business Value까지",
    "changes": "Section divider with the current agenda section highlighted.",
    "visualAudit": "UPDATED",
    "kind": "divider",
    "section": "Demo & Business Value",
    "sectionNumber": "04",
    "order": 24
  },
  {
    "order": 25,
    "file": "2page.html",
    "title": "Demo — Business Context & Challenges",
    "status": "existing",
    "purpose": "Define the business challenges and goals for the demo organization.",
    "keyMessage": "Enterprise work can move from manual coordination to controlled autonomy.",
    "changes": "Moved to Demo as the organizational business context.",
    "visualAudit": "TOO TEXT-HEAVY",
    "section": "Demo & Business Value",
    "sectionNumber": "04"
  },
  {
    "order": 26,
    "file": "cross-team-expanded.html",
    "title": "Demo — Cross-Team Operating Model · SCM Team 확대",
    "status": "revised",
    "purpose": "Combine team placement and the shared AI operating model in one zoomed SCM Team view.",
    "keyMessage": "Team-specific knowledge and execution connect through a common enterprise knowledge foundation.",
    "changes": "Combined team placement and original Shared AI Foundation layout; replaces former slides 25 and 26.",
    "visualAudit": "UPDATED",
    "section": "Demo & Business Value",
    "sectionNumber": "04"
  },
  {
    "order": 27,
    "file": "22page.html",
    "title": "Demo — Autonomous SCM Scenarios",
    "status": "revised",
    "beforeFile": "../lges_customer/18page.html",
    "purpose": "Demonstrate increasing levels of autonomy in SCM scenarios.",
    "keyMessage": "The scenarios progress from a task to exception resolution to orchestration.",
    "changes": "Moved into the proof section.",
    "visualAudit": "TOO TEXT-HEAVY",
    "agents": "영업 · 생산 · 구매 Agent",
    "section": "Demo & Business Value",
    "sectionNumber": "04"
  },
  {
    "order": 28,
    "file": "demo-video-01-inbound.html",
    "title": "Demo 01 — Inbound Process Adaptation",
    "status": "revised",
    "purpose": "Show inbound Excel format adaptation, App Builder code changes and Sandbox validation.",
    "keyMessage": "입고 Excel 양식 변경 → App Builder 코드 수정 → Sandbox 검증",
    "changes": "Embedded a 63-second edited demo with Korean captions, focus boxes, trimmed waits and variable playback speeds.",
    "section": "Demo & Business Value",
    "sectionNumber": "04"
  },
  {
    "order": 29,
    "file": "demo-video-02-exception.html",
    "title": "Demo 02 — SCM Exception Handling",
    "status": "new",
    "purpose": "Provide a dedicated video placeholder for this SCM demo case.",
    "keyMessage": "지식·이력 기반 입고 지연·재고·납기 Risk 대응",
    "changes": "Added a 16:9 video insertion area after the scenario overview.",
    "section": "Demo & Business Value",
    "sectionNumber": "04"
  },
  {
    "order": 30,
    "file": "demo-video-03-orchestration.html",
    "title": "Demo 03 — Demand-to-Supply Orchestration",
    "status": "new",
    "purpose": "Provide a dedicated video placeholder for this SCM demo case.",
    "keyMessage": "수요·납기 변경의 생산·구매·물류 영향 분석과 실행",
    "changes": "Added a 16:9 video insertion area after the scenario overview.",
    "section": "Demo & Business Value",
    "sectionNumber": "04"
  },
  {
    "order": 31,
    "file": "23page.html",
    "title": "Why SAP BAIP + Harness",
    "status": "revised",
    "purpose": "Close with SAP BAIP TCO and OPEX efficiency and Harness-driven business value.",
    "keyMessage": "비용 효율화 → 실행 가속 → 업무 가치 창출",
    "changes": "Keyword-led two-column conclusion: SAP BAIP cost efficiency and Harness business value.",
    "visualAudit": "UPDATED",
    "section": "Demo & Business Value",
    "sectionNumber": "04"
  }
];
