/* Review-only manifest. Exporters must render only the files named by `file`. */
const slides = [
  { order: 1, file: "1page.html", title: "SAP BTP Agent Demo for Autonomous Enterprise", status: "existing", purpose: "Open the deck with the autonomous enterprise ambition.", keyMessage: "SAP BTP provides the foundation for context-aware enterprise agents.", changes: "Retained as the opening cover." },
  { order: 2, file: "2page.html", title: "Toward an Autonomous Enterprise", status: "existing", purpose: "Frame the shift from fragmented manual work to autonomous operations.", keyMessage: "Enterprise work can move from manual coordination to controlled autonomy.", changes: "Retained as the opening vision slide." },
  { order: 3, file: "3page.html", title: "Business Context for Enterprise AI", status: "new", purpose: "Explain why enterprise AI needs more than a generic LLM.", keyMessage: "Autonomous AI requires data, process, knowledge, identity, and policy context.", changes: "New bridge between the autonomous-enterprise vision and the solution foundation." },
  { order: 4, file: "4page.html", title: "The Foundation of Connected AI Applications", status: "revised", beforeFile: "../lges_customer/3page.html", purpose: "Show how shared enterprise intelligence supports applications and agents.", keyMessage: "Connected applications build on one shared AI and knowledge foundation.", changes: "Moved after business context and reframed as the solution vision." },
  { order: 5, file: "5page.html", title: "Connected AI Applications Across Teams", status: "revised", beforeFile: "../lges_customer/4page.html", purpose: "Show cross-functional autonomy rather than isolated AI applications.", keyMessage: "Teams share context, orchestration, governance, and reusable capabilities.", changes: "Moved directly after the shared foundation." },
  { order: 6, file: "6page.html", title: "From Business Request to Autonomous Execution", status: "new", purpose: "Connect all major capabilities into one business flow.", keyMessage: "A request travels through context, planning, coordination, validation, and outcome.", changes: "New end-to-end story slide." },
  { order: 7, file: "7page.html", title: "Agentic Execution Loop", status: "new", purpose: "Make the internal loop of an autonomous agent easy to understand.", keyMessage: "Agents understand, retrieve, reason, plan, execute, validate, and escalate.", changes: "New operational model slide." },
  { order: 8, file: "8page.html", title: "Capability Overview", status: "new", purpose: "Group technologies by the role they play in connected autonomy.", keyMessage: "Experience, context, build, and execution work as one capability system.", changes: "New orientation slide before detailed capability pages." },
  { order: 9, file: "9page.html", title: "Knowledge Layer: HANA Knowledge Graph", status: "revised", beforeFile: "../lges_customer/7page.html", purpose: "Explain how enterprise meaning and relationships become agent context.", keyMessage: "A knowledge graph connects distributed information to business meaning.", changes: "Repositioned in the knowledge layer; title made message-led." },
  { order: 10, file: "10page.html", title: "Experience Layer: Joule", status: "revised", beforeFile: "../lges_customer/8page.html", purpose: "Show the SAP-facing entry point for AI-assisted work.", keyMessage: "Joule brings AI into the SAP work experience.", changes: "Title made message-led and moved into the capability narrative." },
  { order: 11, file: "11page.html", title: "Execution Layer: Harness", status: "revised", beforeFile: "../lges_customer/9page.html", purpose: "Introduce coordinated execution as a capability, not an isolated product.", keyMessage: "Harness turns a request into coordinated work.", changes: "Title made message-led and placed before Deep Agent and A2A." },
  { order: 12, file: "12page.html", title: "Harness Deep Agent", status: "revised", beforeFile: "../lges_customer/10page.html", purpose: "Explain planning beyond a single assistant response.", keyMessage: "Deep Agent creates accountable plans across a complex task.", changes: "Title made message-led within the orchestration progression." },
  { order: 13, file: "13page.html", title: "Harness A2A", status: "revised", beforeFile: "../lges_customer/11page.html", purpose: "Explain collaboration between specialized agents and applications.", keyMessage: "A2A coordinates specialists across the business process.", changes: "Title made message-led within the orchestration progression." },
  { order: 14, file: "14page.html", title: "Human + Agent Operating Model", status: "new", purpose: "Show that autonomy scales with human control and risk.", keyMessage: "People govern intent and exceptions while agents execute within guardrails.", changes: "New controlled-autonomy maturity model." },
  { order: 15, file: "15page.html", title: "Enterprise AI Governance", status: "new", purpose: "Show the controls required to operate agents responsibly.", keyMessage: "Governance is built into how agents are built, run, and observed.", changes: "New build-run-observe governance model." },
  { order: 16, file: "16page.html", title: "Why SAP BTP?", status: "revised", beforeFile: "../lges_customer/15page.html", purpose: "Connect the autonomous model to SAP BTP's enterprise platform value.", keyMessage: "SAP BTP combines business context, integration, and extension capabilities.", changes: "Moved after the operating model and governance rationale." },
  { order: 17, file: "17page.html", title: "Why SAP BTP for Operations?", status: "revised", beforeFile: "../lges_customer/16page.html", purpose: "Extend the BTP case to operating and lifecycle needs.", keyMessage: "Enterprise operations require lifecycle, observability, and integration discipline.", changes: "Moved after the BTP value proposition." },
  { order: 18, file: "18page.html", title: "Reference SAP BTP Architecture & Cost", status: "revised", beforeFile: "../lges_customer/12page.html", purpose: "Provide the reference architecture after the business rationale is established.", keyMessage: "The platform architecture supports the connected autonomous model.", changes: "Reordered into the architecture section." },
  { order: 19, file: "19page.html", title: "BTP Standard Architecture", status: "revised", beforeFile: "../lges_customer/13page.html", purpose: "Show the standard architecture context for the solution.", keyMessage: "The solution fits within a BTP standard architecture.", changes: "Reordered into the architecture section." },
  { order: 20, file: "20page.html", title: "SAP BTP Kyma App-in-App Portal Architecture", status: "revised", beforeFile: "../lges_customer/14page.html", purpose: "Show the implementation architecture for the portal experience.", keyMessage: "The portal architecture operationalizes the connected experience on BTP.", changes: "Reordered into the architecture section." },
  { order: 21, file: "21page.html", title: "Autonomous App-in-App Demo", status: "revised", beforeFile: "../lges_customer/17page.html", purpose: "Introduce the demonstration as proof of the operating model.", keyMessage: "The demo makes the autonomous model tangible in an App-in-App experience.", changes: "Moved after architecture as the proof section opener." },
  { order: 22, file: "22page.html", title: "Autonomous SCM Demo", status: "revised", beforeFile: "../lges_customer/18page.html", purpose: "Demonstrate increasing levels of autonomy in SCM scenarios.", keyMessage: "The scenarios progress from a task to exception resolution to orchestration.", changes: "Moved into the proof section." },
  { order: 23, file: "23page.html", title: "Business Value: Before vs Autonomous", status: "new", purpose: "Close with the operational value of controlled autonomy.", keyMessage: "Agents reduce coordination work so people can focus on decisions and exceptions.", changes: "New conclusion slide." }
];

/* Visual simplification audit — review-only, never part of an export. */
const visualAudit = {
  1:"KEEP VISUAL", 2:"TOO TEXT-HEAVY", 3:"SIMPLIFY", 4:"REDESIGN · TOO UI-LIKE",
  5:"REDESIGN", 6:"REDESIGN", 7:"SIMPLIFY", 8:"SIMPLIFY", 9:"TOO TEXT-HEAVY",
  10:"TOO TEXT-HEAVY", 11:"TOO TEXT-HEAVY", 12:"REDESIGN", 13:"REDESIGN",
  14:"SIMPLIFY", 15:"SIMPLIFY", 16:"TOO TEXT-HEAVY", 17:"TOO TEXT-HEAVY",
  18:"KEEP VISUAL", 19:"SIMPLIFY", 20:"SIMPLIFY", 21:"KEEP VISUAL", 22:"TOO TEXT-HEAVY", 23:"SIMPLIFY"
};
slides.forEach(slide => { slide.visualAudit = visualAudit[slide.order]; });
